## Numpy

In [2]:
import numpy as np

## Question 1

Create a new array of 2*2 integers, without initializing entries.

## Question 2
Create a new array of 3*2 float numbers, filled with ones.

## Question 3
Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

## Question 4
Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

## Question 5
Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

## Question 6
Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

## Question 7
Let x be an array<br/> 
[[ 1 2 3]<br/> 
[ 4 5 6].<br/> 
<br/> 
and y be an array <br/> 
[[ 7 8 9]<br/> 
[10 11 12]].<br/> 
Concatenate x and y so that a new array looks like <br/> 
[[1, 2, 3, 7, 8, 9], <br/> 
[4, 5, 6, 10, 11, 12]].

## Question 8
Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

## Question 9
Let x be an array<br/>
[[ 1 2 3 4]<br/>
[ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

## Question 10
Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
[0, 1, 2, 0, 1, 2]].